//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl.Licencias.Medicas.Dominio.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpRecursoUsuarioLicencias {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpRecursoUsuarioLicencias() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cl.Licencias.Medicas.Dominio.Recursos.SpRecursoUsuarioLicencias", typeof(SpRecursoUsuarioLicencias).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRUEBAPAQUETE.USP_GETPERSONAS.
        /// </summary>
        internal static string PRUEBAPAQUETE_USP_GETPERSONAS {
            get {
                return ResourceManager.GetString("PRUEBAPAQUETE.USP_GETPERSONAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USP_ACTUALIZA_PERSONA.
        /// </summary>
        internal static string USP_ACTUALIZA_PERSONA {
            get {
                return ResourceManager.GetString("USP_ACTUALIZA_PERSONA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USP_ELIMINA_PERSONA.
        /// </summary>
        internal static string USP_ELIMINA_PERSONA {
            get {
                return ResourceManager.GetString("USP_ELIMINA_PERSONA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USP_GETPERSONAS.
        /// </summary>
        internal static string USP_GETPERSONAS {
            get {
                return ResourceManager.GetString("USP_GETPERSONAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USP_INSERTA_PERSONA.
        /// </summary>
        internal static string USP_INSERTA_PERSONA {
            get {
                return ResourceManager.GetString("USP_INSERTA_PERSONA", resourceCulture);
            }
        }
    }
}
